### ISSUE TITLE
Library does not work with Glide v4.0

### ISSUE THREAD

**Issue by lsw19921030** [ParkSangGwon/TedBottomPicker#61]
If I imported the latest version Glide (4.0.0) into my own project,
The app will crash when picker tries to open.

The exception is kind of strange, it said the method load() cannot be found in RequestManager class.

Once I imported Glide 3.7.0 instead, it is all fine.

**Comment by ParkSangGwon** [comment]
Please `Reademe.md`
https://github.com/ParkSangGwon/TedBottomPicker#common

You can use your provider without library's image loader
`setImageProvider(ImageProvider)`

**Comment by lsw19921030** [comment]
Please don't assume people don't read readme....

I am meaning that your library is not compatible with Glide version 4.0,
And the call is **within your library,** not my own code.

This is because your library is built upon Glide ver.3.*, 
But Glide has a newer version 4.0 now. if the project compiles Glide 4.0, your library will crashes.

Suggestion: Update your library to using Glide 4.0

**Comment by altaf2892** [comment]
@ParkSangGwon  Please update Glide Lib ..it crashes with `java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/DrawableTypeRequest; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/"My App package name"1/base.apk:classes15.dex)
                                                                         `

**Comment by mk7seo** [comment]
`                .setImageProvider(new TedBottomPicker.ImageProvider() {
                    @Override
                    public void onProvideImage(ImageView imageView, Uri imageUri) {
                        RequestOptions options = new RequestOptions()
                                .centerCrop()
                                .error(R.drawable.placeholder)
                                .priority(Priority.NORMAL);

                        new GlideImageLoader(imageView, new ProgressBar(context)).load(imageUri.getPath(), options);
                    }
                })`

do something like this.

**Comment by mk7seo** [comment]
Do something like this
`                .setImageProvider(new TedBottomPicker.ImageProvider() {
                    @Override
                    public void onProvideImage(ImageView imageView, Uri imageUri) {
                        RequestOptions options = new RequestOptions()
                                .centerCrop()
                                .error(R.drawable.placeholder)
                                .priority(Priority.NORMAL);
                        new GlideImageLoader(imageView, new ProgressBar(context)).load(imageUri.getPath(), options);
                    }
                })`
